// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEOqsafKfkoYSuTvpeSDvEfm7IEZE0Sl0',
    appId: '1:704219314224:web:202a6253d934178d53d5f5',
    messagingSenderId: '704219314224',
    projectId: 'uthtask-aba8f',
    authDomain: 'uthtask-aba8f.firebaseapp.com',
    storageBucket: 'uthtask-aba8f.appspot.com',
    measurementId: 'G-MK2LZR1784',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuUFv5rkM40dzrEkC7izOQNF6kR4808Q8',
    appId: '1:704219314224:android:1308ad5d3f182aac53d5f5',
    messagingSenderId: '704219314224',
    projectId: 'uthtask-aba8f',
    storageBucket: 'uthtask-aba8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQFSHw0ur9Y3wJEQ-wvyOh5sO7s4pcDVw',
    appId: '1:704219314224:ios:d4725a390b52f86c53d5f5',
    messagingSenderId: '704219314224',
    projectId: 'uthtask-aba8f',
    storageBucket: 'uthtask-aba8f.appspot.com',
    iosBundleId: 'com.example.uthTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQFSHw0ur9Y3wJEQ-wvyOh5sO7s4pcDVw',
    appId: '1:704219314224:ios:d4725a390b52f86c53d5f5',
    messagingSenderId: '704219314224',
    projectId: 'uthtask-aba8f',
    storageBucket: 'uthtask-aba8f.appspot.com',
    iosBundleId: 'com.example.uthTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEOqsafKfkoYSuTvpeSDvEfm7IEZE0Sl0',
    appId: '1:704219314224:web:13e96cd16c1f454553d5f5',
    messagingSenderId: '704219314224',
    projectId: 'uthtask-aba8f',
    authDomain: 'uthtask-aba8f.firebaseapp.com',
    storageBucket: 'uthtask-aba8f.appspot.com',
    measurementId: 'G-6G322K8JMT',
  );
}
